### ISSUE TITLE
9.  Connect to LGL

### ISSUE THREAD

**Issue by HTD-CoCA** [cocaseattle/artist-directory#18]

**Comment by Moirvae** [comment]
This would be more on the tech side. Needs research -- a plugin?

**Comment by HTD-CoCA** [comment]
I think you could figure out how to export data from LGL in a CSV file and then upload that into WordPress.

**Comment by Moirvae** [comment]
This is not a one-time export/import issue. This is keeping the user profiles in sync with LGL status.

**Comment by HTD-CoCA** [comment]
Just sent an email to LGL.

**Comment by archisgore** [comment]
This is a bit ill-defined, and I don't necessarily know that we need this as a blocker. What we need to do is track our members and donors in LGL. And LGL does have the ability to import external data.

Why we needed LGL on the old (current website) is because we wanted to process payments and remember membership expiry. If wordpress connects to stripe and accepts payment, then the user-facing side of this should be trivial - members login to wordpress and pay there. That's the only interface they see, and wordpress manages accounts.

On the backend we can have a periodic script to copy over all member data into LGL. But this becomes a non-critical operation. If it fails, it can simply be retried.

That way this issue gets unblocked and LGL needs to take no action.

**Comment by HTD-CoCA** [comment]
Archis have provided the solution to this issue.  I am closing it.
