### ISSUE TITLE
Develop the E-Commerce Feature 

### ISSUE THREAD

**Issue by HTD-CoCA** [cocaseattle/artist-directory#30]

**Comment by linmalex** [comment]
1. recreate (become a member)[https://cocaseattle.org/membershipsignup] page from original website
2. add woocommerce

#### questions
* should artists be able to register for a basic account without paying? ==> allow artists to set up a profile and put the paywall up before publishing the profile instead of before creating the profile
* deadline for this?

**Comment by HTD-CoCA** [comment]
Right now the old site doesn't allow the artist to create a basic profile without paying.  I think before creating the profile so they know what to expect and for convenience?  We don't want surprises after they had already filled out the forms.  That is also a designer question.  Will add Archis to this issue.

**Comment by HTD-CoCA** [comment]
- This  is the link to edit/create/augment more features on the Login Form:  [https://cocamembers.com/wp-admin/post.php?post=12&action=edit](url)

- I have chosen the Login page as our e-commerce page.  The settings for WooCommerce Memberships can be found here:  [https://cocamembers.com/wp-admin/admin.php?page=wc-settings](url)

**Comment by HTD-CoCA** [comment]
There is a registration page that Archis made here: [https://cocamembers.com/wp-admin/post.php?post=9&action=edit](url)

**Comment by HTD-CoCA** [comment]
Completed.  Closing issue.
